### ISSUE TITLE
Đặc tả chức năng

### ISSUE THREAD

**Issue by lenhatthuan** [lenhatthuan/My-Doctor#1]
- Xác định và mô tả từng chức năng 
- Xác định user

**Comment by lenhatthuan** [comment]
Các chức năng quản lý tài khoản
- MobileApp
1. Xác thực bằng mã OTP
> Hệ thống sẽ gửi mã OTP (số ngẫu nhiên) qua tin nhắn điện thoại, người dùng nhập mã này để xác thực. Nếu sau khoảng thời gian nhất định mà vẫn chưa được xác thực thì mã này sẽ bị vô hiệu hóa. Khi đó người dùng yêu cầu hệ thống gửi lại mã OTP mới để xác thực lại.
2. Đăng ký
> Người dùng đăng ký tài khoản bằng số điện thoại và mật khẩu. Nếu số điện thoại này chưa được đăng ký thì hệ thống sẽ xác thực tài khoản trên bằng mã OTP.
3. Quên mật khẩu
> Khi quên mật khẩu đăng nhập, người dùng có thể đổi mật khẩu bằng cách gửi số điện thoại và mật khẩu mới để yêu cầu hệ thống xác nhận tài khoản. Nếu tài khoản có tồn tại, hệ thống sẽ gửi mã OTP để xác thực.
4. Cập nhật thông tin cá nhân
> Người dùng có thể cập nhật các thông tin cá nhân như avatar, họ và tên, năm sinh, địa chỉ, giới tính bản thân sau khi đăng nhập
5. Đổi mật khẩu
> Người dùng có thể đổi mật khẩu sau khi đăng nhập bằng cách xác thực tài khoản với mật khẩu mới thông qua xác thực mã OTP.
- Web
1. Đăng nhập
> Bác sĩ và y tá đều được cấp tài khoản đăng nhập gồm tên đăng nhập và mật khẩu. Khi đăng nhập thành công thì hệ thống sẽ chuyển hướng theo từng loại tài khoản.

**Comment by lenhatthuan** [comment]
Các chức năng chính:
- MobileApp
1. Chẩn đoán khoa
> Hệ thống hiển thị danh sách các triệu chứng để người dùng chọn. Dựa trên danh sách câu trả lời, hệ thống áp dụng thuật toán để đề xuất các khoa mà người dùng nên khám bệnh.   
2. Đặt lịch khám bệnh theo khoa
> Người dùng tự chọn hoặc xem đề xuất từ chẩn đoán khoa để chọn khoa và dựa trên nhu cầu của mình để chọn ngày, thời gian, phòng khám bệnh.
3. Theo dõi STT khám bệnh
> Sau khi đặt lịch khám, người dùng sẽ nhận được STT khám bệnh của mình gồm các thông tin như ngày, phòng, giờ dự kiến khám bệnh. Ngoài ra, người dùng còn xem được STT khám bệnh hiện tại và hệ thống sẽ thông báo khi sắp đến STT của người dùng.
4. Đóng viện phí online
> Phí khám bệnh có thể được thanh toán online qua momo,paypal
5. Xem bệnh án
> Bệnh nhân có thể xem bệnh án của mình
- Web
1. Theo dõi và cập nhật bệnh án
> Bác sĩ có thể xem và cập nhật thêm thông tin vào bệnh án online của bệnh nhân mình phụ trách
2. Cập nhật tình trạng STT khám bệnh
> Khi bác sĩ khám đến người kế tiếp thì phải cập nhật lại tình trạng STT khám bệnh.
3. Cập nhật STT xét nghiệm
> Khi bác sĩ yêu cầu bệnh nhân xét nghiệm, y tá sẽ nhập STT xét nghiệm cho bệnh nhân

**Comment by yenlee38** [comment]
Update chức năng Đóng viện phí online:
>Phí khám bệnh có thể được thanh toán online qua momo, Banking online. Người dùng có thể tra mã hóa đơn khám bệnh để thực hiện thanh toán hoặc quét mã QR.

Update các chức năng chính:
6. Theo dõi sức khỏe:
      >Người dùng có thể update chiều cao, cân nặng để tính BMI, update nhịp tim, tâm trương, tâm thu và cũng có thể note lại tâm trạng của mình theo ngày. Người dùng có thể xem tất cả danh sách theo ngày, đã update, thống kê theo ngày, tháng, năm. Đặt lời nhắc cập nhập thông tin hàng ngày (đo nhịp tim, cập nhập tâm trạng, …)

7. Tư vấn bác sĩ:
	> Chức năng này cung cấp cho người dùng môi trường để hỏi đáp với bác sĩ về bệnh và có thể gửi hồ sơ bệnh án của mình để bác sĩ theo dõi.
8. Mua thuốc online:
	> Người dùng có thể chụp hóa đơn thuốc, hoặc lấy hóa đơn thuốc trong hồ sơ bệnh án của mình để mua thuốc online qua hệ thống.

Web:
4. Trả lời tư vấn bệnh nhân
 > Bác sĩ tư vấn cho bệnh nhân thông qua message

5. Kê đơn thuốc
 >Bác sĩ kê đơn thuốc cho bệnh nhân

**Comment by yenlee38** [comment]
Link doc: https://bitly.com.vn/6325v2
