### ISSUE TITLE
Thiết kế database

### ISSUE THREAD

**Issue by lenhatthuan** [lenhatthuan/My-Doctor#3]
- Vẽ lược đồ ERD
- Viết file sql
- Kết nối CSDL với project

**Comment by yenlee38** [comment]
github Server: https://github.com/yenlee38/my-doctor-api

**Comment by yenlee38** [comment]
[my-doctor-sever.txt](https://github.com/lenhatthuan/My-Doctor/files/6950958/my-doctor-sever.txt)
File sql

**Comment by yenlee38** [comment]
[my-doctor-sever.txt](https://github.com/lenhatthuan/My-Doctor/files/6969840/my-doctor-sever.txt)
File sql

**Comment by yenlee38** [comment]
Link ERD: https://drive.google.com/file/d/1_ys77hwOIB-WbiUn3-VzKMj9TO8jAySI/view?usp=sharing

**Comment by phunghx** [comment]
@yenlee38 @lenhatthuan  có mô hình các bảng trong database và mối quan hệ không

**Comment by yenlee38** [comment]
@phunghx dạ thầy ơi, mục này có phải là class diagram không ạ, tụi em có tại 1 issue Vẽ class diagram

**Comment by lenhatthuan** [comment]
![ERD](https://user-images.githubusercontent.com/73833550/133546513-a4b5eb80-fe8c-448f-95f4-12ec2460a407.png)
