### ISSUE TITLE
Vẽ class diagram

### ISSUE THREAD

**Issue by lenhatthuan** [lenhatthuan/My-Doctor#4]
Nếu project quá nhiều class, có thể đổi thành vẽ component diagram

**Comment by lenhatthuan** [comment]
Gộp các class thành các component:
- AccountManagement: https://drive.google.com/file/d/1Pe3WIzZgGJ7hWuRjPBeQpLqHbX0dkqAz/view?usp=sharing
- FollowHealthy: https://drive.google.com/file/d/12qM0DNmT_AStgHInarOyo5Sh5FMI7X4Z/view?usp=sharing
- Main: https://drive.google.com/file/d/1tONf9whZzF5xKLxCrMYWP-1NS35U5AB0/view?usp=sharing
- Payment: https://drive.google.com/file/d/1kM6u8e0X5XbelKWVOwt5d0H35GpsxeDX/view?usp=sharing

**Comment by yenlee38** [comment]
![image](https://user-images.githubusercontent.com/59739028/140834251-7a44a008-5798-4eaf-bc08-85d8f25d9d47.png)

**Comment by yenlee38** [comment]
![Uploading 251809298_303770934905002_2989655932997385656_n.png…]()

**Comment by yenlee38** [comment]
![251809298_303770934905002_2989655932997385656_n](https://user-images.githubusercontent.com/59739028/140834756-58fafed9-6a93-4963-b55b-034f2866080a.png)
Component nhỏ về theo dõi sức khỏe trong class diagram chính

**Comment by yenlee38** [comment]
![251583918_410279667255967_6987434929332794479_n](https://user-images.githubusercontent.com/59739028/140834826-ed2db5f5-7dba-421a-9c21-608881ba3753.png)
Component nhỏ về đặt lịch khám bệnh theo bác sĩ
