### ISSUE TITLE
Tìm hiểu công nghệ

### ISSUE THREAD

**Issue by lenhatthuan** [lenhatthuan/My-Doctor#5]
- Xác định công nghệ 
- Cài đặt môi trường lập trinh
- Tìm hiểu một số component cơ bản của React Native
- Tìm hiểu NodeJS vào API

**Comment by lenhatthuan** [comment]
Xác định công nghệ
- API: NodeJS, React Native
- Môi trường lập trình: VSCode
- Database: MySQL, Firebase, SQLite

**Comment by lenhatthuan** [comment]
Cài đặt môi trường lập trình
- Cài đặt NodeJS: https://nodejs.org/en/
- Cài đặt VSCode: https://code.visualstudio.com/

**Comment by lenhatthuan** [comment]
Lập trình React Native cơ bản: https://reactnative.dev/

**Comment by yenlee38** [comment]
Doc của API : https://www.bezkoder.com/node-js-rest-api-express-mysql/#Setup_Express_web_server

**Comment by phunghx** [comment]
@yenlee38  @lenhatthuan  Viết file báo cáo riêng của nhóm về các công nghệ này

**Comment by yenlee38** [comment]
@phunghx  Dạ thầy

**Comment by yenlee38** [comment]
@phunghx Thầy ơi tụi em gửi file báo báo https://docs.google.com/document/d/1zFLNJpSpFDFXynsCOy0-96J7fKGSgG99iRdI_NWwKd4/edit?usp=sharing
