### ISSUE TITLE
Vẽ mockup giao diện

### ISSUE THREAD

**Issue by lenhatthuan** [lenhatthuan/My-Doctor#6]
Link mockup: https://www.figma.com/file/0wGSeoTnJ0cdHNmy5FtauQ/V-1

**Comment by yenlee38** [comment]
Link Figma mockup giao diện: https://www.figma.com/file/0wGSeoTnJ0cdHNmy5FtauQ/V-1?node-id=0%3A1

**Comment by phunghx** [comment]
@yenlee38 @lenhatthuan copy giao diện đã thiết kế vào 1 file báo cáo, đánh số các control, loại control, chức năng của control

**Comment by lenhatthuan** [comment]
@phunghx Thầy ơi tụi em gửi file báo báo mockup:
[GUI_MyDoctor.docx](https://github.com/lenhatthuan/My-Doctor/files/7192349/GUI_MyDoctor.docx)
