### ISSUE TITLE
Chức năng Đăng nhập

### ISSUE THREAD

**Issue by lenhatthuan** [lenhatthuan/My-Doctor#8]
- Viết kịch bản usecase và vẽ sequence diagram
- Lập trình

**Comment by yenlee38** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/PC/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/PC/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/PC/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:36.0pt;word-wrap:break-word'>




Name | Đăng nhập
-- | --
Brief description | Người   dùng đăng nhập vào hệ thống.
Actor(s) | Người   dùng (bệnh nhân), Bác sĩ, Y tá
Pre-conditions | Người   dùng đã được tạo tài khoản trong hệ thống.
Post-conditions | Nếu   đăng nhập thành công: Người dùng được xác thực và hệ thống hiển thị nội dung   trang chủ.   Nếu   đăng nhập không thành công: Người dùng không truy cập được vào hệ thống dành   cho người dùng có tài khoản.
Flow of events |  
Basic   flow | Use   case bắt đầu khi người dùng cần thực hiện chức năng nào đó của hệ thống cần xác   thực quyền truy cập:   1.       Hệ thống hiển thị cửa sổ cho người dùng nhập số điện   thoại và password.   2.       Người dùng nhập SĐT và password.   3.       Hệ thống xác thực SĐT và password, sau đó gửi mã OTP   để xác nhận.   4.       Hệ thống xác định vai trò của người dùng.    5.       Hệ thống mở màn hình trang chủ và mở các chức năng   được phép truy cập của người dùng.
Alternative   flow | Nếu   người dùng nhập sai SĐT/password/mã OTP. Những công việc sau được thực hiện:   1.       Hệ thống mô tả lý do xác thực bị sai.   2.       Hệ thống lưu ý người dùng đăng nhập lại.   3.       Khi người dùng nhập lại SĐT và password hoặc mã OTP ,   bước 3 ở Basic flow được thực hiện.
Extension point | Không   có.




</body>

</html>

**Comment by yenlee38** [comment]
![Đăng nhập](https://user-images.githubusercontent.com/59739028/129571896-bc561aa8-2885-44c6-b2a1-60d4a6323143.png)
